name: Discussion Comment on Edit

on:
  discussion:
    types: [edited]
  discussion_comment:
    types: [edited]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    if: github.event.action == 'edited'
    
    permissions:
      discussions: write
      pull-requests: read
      issues: read
      contents: read
      
    steps:
      - name: Add comment to discussion
        uses: actions/github-script@v7
        with:
          script: |
            const query = `
              mutation AddDiscussionComment($discussionId: ID!, $body: String!) {
                addDiscussionComment(input: {discussionId: $discussionId, body: $body}) {
                  comment {
                    id
                    databaseId
                    body
                  }
                }
              }
            `;
            
            const variables = {
              discussionId: context.payload.discussion.node_id,
              body: `---
            
            📝 **${context.eventName === 'discussion' ? 'Discussion' : 'Comment'} was edited**
            
            This ${context.eventName === 'discussion' ? 'discussion' : 'comment'} was modified on ${context.payload.discussion.updated_at || context.payload.comment.updated_at}.
            
            *Original author: @${context.payload.discussion.user.login || context.payload.comment.user.login}*
            *Edited by: @${context.actor}*
            
            > 💡 This is an automated comment added when discussion messages are edited.`
            };
            
            await github.graphql(query, variables);
