name: Discussion Comment on Edit

on:
  discussion:
    types: [edited]
  discussion_comment:
    types: [edited]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    if: github.event.action == 'edited'
    
    permissions:
      discussions: write
      pull-requests: read
      issues: read
      contents: read
      
    steps:
      - name: Add comment to discussion
        uses: actions/github-script@v7
        with:
          script: |
            const query = `
              mutation AddDiscussionComment($discussionId: ID!, $body: String!) {
                addDiscussionComment(input: {discussionId: $discussionId, body: $body}) {
                  comment {
                    id
                    databaseId
                    body
                  }
                }
              }
            `;
            
            const variables = {
              discussionId: context.payload.discussion.node_id,
              body: `<!-- Edited by @${context.actor} | Comment ID: ${context.payload.comment ? context.payload.comment.id : context.payload.discussion.id} -->\n\n${context.payload.comment ? context.payload.comment.body : context.payload.discussion.body}`
            };
            
            await github.graphql(query, variables);
